# Generated by Django 5.1.7 on 2025-04-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('exercise_type', models.CharField(choices=[('Strength', 'Strength'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility')], default='STRENGTH', max_length=11)),
                ('equipment_needed', models.CharField(blank=True, max_length=100)),
                ('primary_muscle_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_exercises', to='exercises.musclegroup')),
                ('secondary_muscle_groups', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.musclegroup')),
            ],
        ),
    ]
