# Generated by Django 5.1.7 on 2025-04-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('muscle_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_exercises', to='muscle_groups.musclegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='secondary_exercises', to='muscle_groups.musclegroup'),
        ),
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
    ]
