# Generated by Django 5.1.7 on 2025-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repetitions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
