# Generated by Django 5.1.7 on 2025-04-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_weight_alter_exercise_repetitions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment_needed',
        ),
    ]
