# Generated by Django 5.1.7 on 2025-05-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_slug'),
        ('muscle_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_muscle_groups', to='muscle_groups.musclegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscle_groups',
            field=models.ManyToManyField(blank=True, related_name='secondary_muscle_groups', to='muscle_groups.musclegroup'),
        ),
    ]
