# Generated by Django 5.1.7 on 2025-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
