# Generated by Django 5.1.7 on 2025-04-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_options_workout_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
    ]
